In [32]:
import pandas as pd

In [31]:
redfin_original_csv = pd.read_csv('/redfin_neighborhood_match_data.csv')
redfin_original_csv.head()

FileNotFoundError: [Errno 2] File redfin_neighborhood_match_data.csv does not exist: 'redfin_neighborhood_match_data.csv'

In [3]:
# list(redfin_original_csv.columns)

In [4]:
redfin_columns_removed = redfin_original_csv[['PROPERTY TYPE', 'ADDRESS', 'CITY', 'STATE OR PROVINCE', 'ZIP OR POSTAL CODE', 'PRICE', 'BEDS', 'BATHS', 'LOCATION', 'SQUARE FEET', 'YEAR BUILT', '$/SQUARE FEET', 'HOA/MONTH', 'LATITUDE', 'LONGITUDE']]
redfin_columns_removed.head()

,PROPERTY TYPE,ADDRESS,CITY,STATE OR PROVINCE,ZIP OR POSTAL CODE,PRICE,BEDS,BATHS,LOCATION,SQUARE FEET,YEAR BUILT,$/SQUARE FEET,HOA/MONTH,LATITUDE,LONGITUDE
0,Condo/Co-op,1548 Jones St,San Francisco,CA,94109,1400000,2.0,2.0,Nob Hill,1158.0,1910.0,1209.0,339.0,37.795687,-122.414775
1,Condo/Co-op,2200 Market St #402,San Francisco,CA,94114,1150000,1.0,1.5,Duboce Triangle,825.0,2014.0,1394.0,627.0,37.765789,-122.431598
2,Condo/Co-op,2040 Franklin St #1004,San Francisco,CA,94109,998000,1.0,1.0,Pacific Heights,919.0,1966.0,1086.0,942.0,37.793519,-122.424316
3,Condo/Co-op,1425 Vallejo St #205,San Francisco,CA,94109,1349000,2.0,2.0,Russian Hill,1034.0,1982.0,1305.0,744.0,37.796735,-122.420827
4,Condo/Co-op,260 King St #903,San Francisco,CA,94107,1249000,2.0,2.0,Mission Bay,1286.0,2004.0,971.0,932.0,37.777642,-122.393418

In [5]:
redfin_columns_removed["COORDINATES"] = redfin_columns_removed["LATITUDE"].astype(str) +"," + redfin_columns_removed["LONGITUDE"].astype(str)
redfin_columns_removed.head()

/Users/cynthiakellogg/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,PROPERTY TYPE,ADDRESS,CITY,STATE OR PROVINCE,ZIP OR POSTAL CODE,PRICE,BEDS,BATHS,LOCATION,SQUARE FEET,YEAR BUILT,$/SQUARE FEET,HOA/MONTH,LATITUDE,LONGITUDE,COORDINATES
0,Condo/Co-op,1548 Jones St,San Francisco,CA,94109,1400000,2.0,2.0,Nob Hill,1158.0,1910.0,1209.0,339.0,37.795687,-122.414775,"37.7956865,-122.4147746"
1,Condo/Co-op,2200 Market St #402,San Francisco,CA,94114,1150000,1.0,1.5,Duboce Triangle,825.0,2014.0,1394.0,627.0,37.765789,-122.431598,"37.7657893,-122.431598"
2,Condo/Co-op,2040 Franklin St #1004,San Francisco,CA,94109,998000,1.0,1.0,Pacific Heights,919.0,1966.0,1086.0,942.0,37.793519,-122.424316,"37.7935189,-122.4243158"
3,Condo/Co-op,1425 Vallejo St #205,San Francisco,CA,94109,1349000,2.0,2.0,Russian Hill,1034.0,1982.0,1305.0,744.0,37.796735,-122.420827,"37.7967355,-122.42082659999998"
4,Condo/Co-op,260 King St #903,San Francisco,CA,94107,1249000,2.0,2.0,Mission Bay,1286.0,2004.0,971.0,932.0,37.777642,-122.393418,"37.7776422,-122.39341809999999"

In [6]:
redfin_location_combined = pd.DataFrame(redfin_columns_removed)

In [7]:
redfin_location_combined

,PROPERTY TYPE,ADDRESS,CITY,STATE OR PROVINCE,ZIP OR POSTAL CODE,PRICE,BEDS,BATHS,LOCATION,SQUARE FEET,YEAR BUILT,$/SQUARE FEET,HOA/MONTH,LATITUDE,LONGITUDE,COORDINATES
0,Condo/Co-op,1548 Jones St,San Francisco,CA,94109,1400000,2.0,2.0,Nob Hill,1158.0,1910.0,1209.0,339.0,37.795687,-122.414775,"37.7956865,-122.4147746"
1,Condo/Co-op,2200 Market St #402,San Francisco,CA,94114,1150000,1.0,1.5,Duboce Triangle,825.0,2014.0,1394.0,627.0,37.765789,-122.431598,"37.7657893,-122.431598"
2,Condo/Co-op,2040 Franklin St #1004,San Francisco,CA,94109,998000,1.0,1.0,Pacific Heights,919.0,1966.0,1086.0,942.0,37.793519,-122.424316,"37.7935189,-122.4243158"
3,Condo/Co-op,1425 Vallejo St #205,San Francisco,CA,94109,1349000,2.0,2.0,Russian Hill,1034.0,1982.0,1305.0,744.0,37.796735,-122.420827,"37.7967355,-122.42082659999998"
4,Condo/Co-op,260 King St #903,San Francisco,CA,94107,1249000,2.0,2.0,Mission Bay,1286.0,2004.0,971.0,932.0,37.777642,-122.393418,"37.7776422,-122.39341809999999"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,Condo/Co-op,155 Harriet St #8,San Francisco,CA,94103,999000,2.0,2.0,South of Market,NaN,2001.0,NaN,652.0,37.777616,-122.404989,"37.7776155,-122.4049895"
346,Condo/Co-op,769 19th Ave,San Francisco,CA,94121,1425000,2.0,1.5,Central Richmond,1400.0,1922.0,1018.0,250.0,37.773474,-122.478137,"37.7734744,-122.47813670000001"
347,Condo/Co-op,355 Buena Vista Ave Unit 512W,San Francisco,CA,94117,1425000,2.0,2.0,Buena Vista Park,1030.0,1986.0,1383.0,858.0,37.767181,-122.440133,"37.7671808,-122.44013290000001"
348,Single Family Residential,2587 41st Ave,San Francisco,CA,94116,1095000,3.0,2.0,Outer Parkside,1655.0,1952.0,662.0,NaN,37.738546,-122.499229,"37.738546,-122.49922859999998"
349,Condo/Co-op,1160 Mission St #1907,San Francisco,CA,94103,1200000,2.0,2.0,South of Market,1043.0,2008.0,1151.0,915.0,37.778704,-122.412634,"37.7787037,-122.4126341"

In [8]:
redfin_location_combined['YEAR BUILT'] = redfin_location_combined['YEAR BUILT'].astype(str)

In [9]:
redfin_location_combined['BUILT YEAR'] = redfin_location_combined['YEAR BUILT'].astype(str).str[:4]
redfin_location_combined

,PROPERTY TYPE,ADDRESS,CITY,STATE OR PROVINCE,ZIP OR POSTAL CODE,PRICE,BEDS,BATHS,LOCATION,SQUARE FEET,YEAR BUILT,$/SQUARE FEET,HOA/MONTH,LATITUDE,LONGITUDE,COORDINATES,BUILT YEAR
0,Condo/Co-op,1548 Jones St,San Francisco,CA,94109,1400000,2.0,2.0,Nob Hill,1158.0,1910.0,1209.0,339.0,37.795687,-122.414775,"37.7956865,-122.4147746",1910
1,Condo/Co-op,2200 Market St #402,San Francisco,CA,94114,1150000,1.0,1.5,Duboce Triangle,825.0,2014.0,1394.0,627.0,37.765789,-122.431598,"37.7657893,-122.431598",2014
2,Condo/Co-op,2040 Franklin St #1004,San Francisco,CA,94109,998000,1.0,1.0,Pacific Heights,919.0,1966.0,1086.0,942.0,37.793519,-122.424316,"37.7935189,-122.4243158",1966
3,Condo/Co-op,1425 Vallejo St #205,San Francisco,CA,94109,1349000,2.0,2.0,Russian Hill,1034.0,1982.0,1305.0,744.0,37.796735,-122.420827,"37.7967355,-122.42082659999998",1982
4,Condo/Co-op,260 King St #903,San Francisco,CA,94107,1249000,2.0,2.0,Mission Bay,1286.0,2004.0,971.0,932.0,37.777642,-122.393418,"37.7776422,-122.39341809999999",2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,Condo/Co-op,155 Harriet St #8,San Francisco,CA,94103,999000,2.0,2.0,South of Market,NaN,2001.0,NaN,652.0,37.777616,-122.404989,"37.7776155,-122.4049895",2001
346,Condo/Co-op,769 19th Ave,San Francisco,CA,94121,1425000,2.0,1.5,Central Richmond,1400.0,1922.0,1018.0,250.0,37.773474,-122.478137,"37.7734744,-122.47813670000001",1922
347,Condo/Co-op,355 Buena Vista Ave Unit 512W,San Francisco,CA,94117,1425000,2.0,2.0,Buena Vista Park,1030.0,1986.0,1383.0,858.0,37.767181,-122.440133,"37.7671808,-122.44013290000001",1986
348,Single Family Residential,2587 41st Ave,San Francisco,CA,94116,1095000,3.0,2.0,Outer Parkside,1655.0,1952.0,662.0,NaN,37.738546,-122.499229,"37.738546,-122.49922859999998",1952
349,Condo/Co-op,1160 Mission St #1907,San Francisco,CA,94103,1200000,2.0,2.0,South of Market,1043.0,2008.0,1151.0,915.0,37.778704,-122.412634,"37.7787037,-122.4126341",2008

In [10]:
redfin_location_combined.head()

,PROPERTY TYPE,ADDRESS,CITY,STATE OR PROVINCE,ZIP OR POSTAL CODE,PRICE,BEDS,BATHS,LOCATION,SQUARE FEET,YEAR BUILT,$/SQUARE FEET,HOA/MONTH,LATITUDE,LONGITUDE,COORDINATES,BUILT YEAR
0,Condo/Co-op,1548 Jones St,San Francisco,CA,94109,1400000,2.0,2.0,Nob Hill,1158.0,1910.0,1209.0,339.0,37.795687,-122.414775,"37.7956865,-122.4147746",1910
1,Condo/Co-op,2200 Market St #402,San Francisco,CA,94114,1150000,1.0,1.5,Duboce Triangle,825.0,2014.0,1394.0,627.0,37.765789,-122.431598,"37.7657893,-122.431598",2014
2,Condo/Co-op,2040 Franklin St #1004,San Francisco,CA,94109,998000,1.0,1.0,Pacific Heights,919.0,1966.0,1086.0,942.0,37.793519,-122.424316,"37.7935189,-122.4243158",1966
3,Condo/Co-op,1425 Vallejo St #205,San Francisco,CA,94109,1349000,2.0,2.0,Russian Hill,1034.0,1982.0,1305.0,744.0,37.796735,-122.420827,"37.7967355,-122.42082659999998",1982
4,Condo/Co-op,260 King St #903,San Francisco,CA,94107,1249000,2.0,2.0,Mission Bay,1286.0,2004.0,971.0,932.0,37.777642,-122.393418,"37.7776422,-122.39341809999999",2004

In [11]:
redfin_year_new = redfin_location_combined[['PROPERTY TYPE', 'ADDRESS', 'CITY', 'STATE OR PROVINCE', 'ZIP OR POSTAL CODE', 'PRICE', 'BEDS', 'BATHS', 'LOCATION', 'SQUARE FEET', '$/SQUARE FEET', 'HOA/MONTH', 'LATITUDE', 'LONGITUDE', 'BUILT YEAR', 'COORDINATES']]

In [12]:
redfin_year_new.head()

,PROPERTY TYPE,ADDRESS,CITY,STATE OR PROVINCE,ZIP OR POSTAL CODE,PRICE,BEDS,BATHS,LOCATION,SQUARE FEET,$/SQUARE FEET,HOA/MONTH,LATITUDE,LONGITUDE,BUILT YEAR,COORDINATES
0,Condo/Co-op,1548 Jones St,San Francisco,CA,94109,1400000,2.0,2.0,Nob Hill,1158.0,1209.0,339.0,37.795687,-122.414775,1910,"37.7956865,-122.4147746"
1,Condo/Co-op,2200 Market St #402,San Francisco,CA,94114,1150000,1.0,1.5,Duboce Triangle,825.0,1394.0,627.0,37.765789,-122.431598,2014,"37.7657893,-122.431598"
2,Condo/Co-op,2040 Franklin St #1004,San Francisco,CA,94109,998000,1.0,1.0,Pacific Heights,919.0,1086.0,942.0,37.793519,-122.424316,1966,"37.7935189,-122.4243158"
3,Condo/Co-op,1425 Vallejo St #205,San Francisco,CA,94109,1349000,2.0,2.0,Russian Hill,1034.0,1305.0,744.0,37.796735,-122.420827,1982,"37.7967355,-122.42082659999998"
4,Condo/Co-op,260 King St #903,San Francisco,CA,94107,1249000,2.0,2.0,Mission Bay,1286.0,971.0,932.0,37.777642,-122.393418,2004,"37.7776422,-122.39341809999999"

In [13]:
redfin_year_new.groupby("LOCATION").count()

,PROPERTY TYPE,ADDRESS,CITY,STATE OR PROVINCE,ZIP OR POSTAL CODE,PRICE,BEDS,BATHS,SQUARE FEET,$/SQUARE FEET,HOA/MONTH,LATITUDE,LONGITUDE,BUILT YEAR,COORDINATES
LOCATION,,,,,,,,,,,,,,,
699 - Not Defined,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Alamo Square,1,1,1,1,1,1,1,1,0,0,0,1,1,1,1
Anza Vista,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Bayview,5,4,5,5,5,5,5,5,4,4,0,5,5,5,5
Bernal Heights,7,7,7,7,7,7,7,7,5,5,1,7,7,7,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Telegraph Hill,3,3,3,3,3,3,3,3,2,2,2,3,3,3,3
Twin Peaks,3,3,3,3,3,3,3,2,3,3,2,3,3,3,3
Van Ness/Civic Center,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Westwood Highlands,2,2,2,2,2,2,2,2,2,2,0,2,2,2,2
Yerba Buena,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8

In [14]:
redfin_year_new.groupby("LOCATION").mean().sort_values("$/SQUARE FEET", ascending=True)

,PRICE,BEDS,BATHS,SQUARE FEET,$/SQUARE FEET,HOA/MONTH,LATITUDE,LONGITUDE
LOCATION,,,,,,,,
Huntington Lake,119000.0,1.00,1.00,608.000000,196.000000,49.0,37.782381,-122.416550
Mission Terrace,1498888.0,5.00,3.00,2432.000000,616.000000,NaN,37.723238,-122.443605
Outer Parkside,1095000.0,3.00,2.00,1655.000000,662.000000,NaN,37.738546,-122.499229
Candlestick Point,728000.0,2.00,2.00,1095.000000,665.000000,540.0,37.711929,-122.388605
Bayview,940800.0,3.20,1.90,1492.500000,683.750000,NaN,37.731585,-122.388062
...,...,...,...,...,...,...,...,...
Russian Hill,2824200.0,2.00,2.20,1963.333333,1457.000000,1352.2,37.800845,-122.421361
Pacific Heights,5792750.0,2.25,2.75,2695.428571,1661.714286,872.0,37.794111,-122.430178
Alamo Square,4998000.0,7.00,5.00,NaN,NaN,NaN,37.777562,-122.434218
Golden Gate Heights,1325000.0,2.00,1.00,NaN,NaN,NaN,37.749079,-122.469579
Ingleside,813500.0,1.50,1.00,NaN,NaN,NaN,37.718520,-122.456018

In [15]:
new_df = redfin_year_new.groupby("LOCATION").mean().sort_values("$/SQUARE FEET", ascending=False)
new_df

,PRICE,BEDS,BATHS,SQUARE FEET,$/SQUARE FEET,HOA/MONTH,LATITUDE,LONGITUDE
LOCATION,,,,,,,,
Pacific Heights,5.792750e+06,2.250000,2.750000,2695.428571,1661.714286,872.0,37.794111,-122.430178
Russian Hill,2.824200e+06,2.000000,2.200000,1963.333333,1457.000000,1352.2,37.800845,-122.421361
Marina,3.627857e+06,2.571429,2.428571,2241.571429,1444.857143,500.4,37.803003,-122.439602
Presidio Heights,5.387500e+06,4.500000,3.500000,3589.000000,1383.000000,104.0,37.789702,-122.449622
Telegraph Hill,2.481667e+06,3.000000,2.166667,758.000000,1361.000000,322.5,37.802988,-122.408114
...,...,...,...,...,...,...,...,...
Mission Terrace,1.498888e+06,5.000000,3.000000,2432.000000,616.000000,NaN,37.723238,-122.443605
Huntington Lake,1.190000e+05,1.000000,1.000000,608.000000,196.000000,49.0,37.782381,-122.416550
Alamo Square,4.998000e+06,7.000000,5.000000,NaN,NaN,NaN,37.777562,-122.434218
Golden Gate Heights,1.325000e+06,2.000000,1.000000,NaN,NaN,NaN,37.749079,-122.469579
Ingleside,8.135000e+05,1.500000,1.000000,NaN,NaN,NaN,37.718520,-122.456018

In [16]:
# find real estate for Lakeshore, Mission, Tenderloin
# df.loc[(df['Color'] == 'Green')

pac_heights_df = redfin_year_new.loc[(redfin_year_new['LOCATION'] == 'Pacific Heights')]

pac_heights_df

,PROPERTY TYPE,ADDRESS,CITY,STATE OR PROVINCE,ZIP OR POSTAL CODE,PRICE,BEDS,BATHS,LOCATION,SQUARE FEET,$/SQUARE FEET,HOA/MONTH,LATITUDE,LONGITUDE,BUILT YEAR,COORDINATES
2,Condo/Co-op,2040 Franklin St #1004,San Francisco,CA,94109,998000,1.0,1.0,Pacific Heights,919.0,1086.0,942.0,37.793519,-122.424316,1966,"37.7935189,-122.4243158"
84,Condo/Co-op,1895 Pacific Ave #104,San Francisco,CA,94109,599000,0.0,1.0,Pacific Heights,512.0,1170.0,440.0,37.794168,-122.426243,1931,"37.7941676,-122.4262431"
107,Condo/Co-op,2100 Green St #704,San Francisco,CA,94123,3495000,2.0,2.0,Pacific Heights,1866.0,1873.0,1618.0,37.796589,-122.433981,1928,"37.796589399999995,-122.4339807"
163,Condo/Co-op,1755 Jackson St #406,San Francisco,CA,94109,2250000,3.0,3.0,Pacific Heights,1906.0,1180.0,750.0,37.793538,-122.424002,1923,"37.793537799999996,-122.4240021"
172,Condo/Co-op,2200 Sacramento St #1305,San Francisco,CA,94115,2050000,1.0,2.0,Pacific Heights,NaN,NaN,682.0,37.790681,-122.429498,1964,"37.790681400000004,-122.42949840000001"
242,Condo/Co-op,1870 Jackson St #301,San Francisco,CA,94109,1650000,2.0,1.0,Pacific Heights,1350.0,1222.0,800.0,37.793859,-122.425854,1931,"37.793859499999996,-122.4258544"
306,Single Family Residential,2341 Vallejo St,San Francisco,CA,94123,6500000,4.0,4.0,Pacific Heights,3685.0,1764.0,NaN,37.794944,-122.435809,1922,"37.7949444,-122.43580870000001"
324,Single Family Residential,2590 Green St,San Francisco,CA,94123,28800000,5.0,8.0,Pacific Heights,8630.0,3337.0,NaN,37.795586,-122.441718,1920,"37.795586,-122.441718"

In [17]:
redfin_year_new.to_csv('../Resources/clean_redfin_data.csv', index = True)

In [18]:
pac_heights_df.describe()

,PRICE,BEDS,BATHS,SQUARE FEET,$/SQUARE FEET,HOA/MONTH,LATITUDE,LONGITUDE
count,8.000000e+00,8.000000,8.00000,7.000000,7.000000,6.00000,8.000000,8.000000
mean,5.792750e+06,2.250000,2.75000,2695.428571,1661.714286,872.00000,37.794111,-122.430178
std,9.477791e+06,1.669046,2.37547,2806.028502,802.113191,401.05062,0.001753,0.006397
min,5.990000e+05,0.000000,1.00000,512.000000,1086.000000,440.00000,37.790681,-122.441718
25%,1.487000e+06,1.000000,1.00000,1134.500000,1175.000000,699.00000,37.793533,-122.434438
50%,2.150000e+06,2.000000,2.00000,1866.000000,1222.000000,775.00000,37.794014,-122.427871
75%,4.246250e+06,3.250000,3.25000,2795.500000,1818.500000,906.50000,37.795105,-122.425470
max,2.880000e+07,5.000000,8.00000,8630.000000,3337.000000,1618.00000,37.796589,-122.424002

In [23]:
mission_df = redfin_year_new.loc[(redfin_year_new['LOCATION'] == 'Inner Mission')]

mission_df

,PROPERTY TYPE,ADDRESS,CITY,STATE OR PROVINCE,ZIP OR POSTAL CODE,PRICE,BEDS,BATHS,LOCATION,SQUARE FEET,$/SQUARE FEET,HOA/MONTH,LATITUDE,LONGITUDE,BUILT YEAR,COORDINATES
10,Condo/Co-op,2987 Harrison St,San Francisco,CA,94110,1325000,3.0,2.0,Inner Mission,1658.0,799.0,180.0,37.749783,-122.411310,1900,"37.749783,-122.4113096"
21,Condo/Co-op,1875 Mission St #108,San Francisco,CA,94103,649000,0.0,1.0,Inner Mission,619.0,1048.0,526.0,37.767101,-122.419446,2014,"37.7671013,-122.41944609999999"
64,Condo/Co-op,1298 Treat Ave,San Francisco,CA,94110,1249000,4.0,2.0,Inner Mission,1250.0,999.0,360.0,37.749378,-122.412712,1900,"37.7493778,-122.4127122"
211,Condo/Co-op,1188 Valencia St #210,San Francisco,CA,94110,889000,1.0,1.0,Inner Mission,NaN,NaN,484.0,37.753920,-122.421016,2018,"37.75392,-122.42101640000001"
226,Condo/Co-op,3418 26th St #11,San Francisco,CA,94110,719000,1.0,1.0,Inner Mission,NaN,NaN,570.0,37.749202,-122.418984,2014,"37.7492018,-122.41898379999999"
265,Multi-Family (2-4 Unit),3132-3136 23rd St,San Francisco,CA,94110,1200000,4.0,3.0,Inner Mission,2191.0,548.0,NaN,37.754182,-122.415061,1900,"37.7541819,-122.4150611"
273,Condo/Co-op,45 Bartlett St #416,San Francisco,CA,94110,698000,1.0,1.0,Inner Mission,517.0,1350.0,540.0,37.755936,-122.419286,2014,"37.7559364,-122.41928600000001"
281,Condo/Co-op,2600 18th St #7,San Francisco,CA,94110,1299000,2.0,2.0,Inner Mission,1304.0,996.0,573.0,37.762136,-122.408479,1999,"37.762136,-122.40847920000002"
294,Single Family Residential,2851 25th St,San Francisco,CA,94110,1895000,3.0,1.5,Inner Mission,1860.0,1019.0,NaN,37.751165,-122.407282,1929,"37.7511649,-122.4072825"
308,Condo/Co-op,755 Capp St,San Francisco,CA,94110,1695000,3.0,1.0,Inner Mission,1890.0,897.0,200.0,37.754276,-122.417223,1900,"37.754276000000004,-122.41722299999999"

In [24]:
mission_df.describe()

,PRICE,BEDS,BATHS,SQUARE FEET,$/SQUARE FEET,HOA/MONTH,LATITUDE,LONGITUDE
count,1.000000e+01,10.000000,10.00000,8.000000,8.000000,8.00000,10.000000,10.000000
mean,1.161800e+06,2.200000,1.55000,1411.125000,957.000000,429.12500,37.754708,-122.415080
std,4.249146e+05,1.398412,0.68516,605.253297,228.568214,162.38177,0.005840,0.004899
min,6.490000e+05,0.000000,1.00000,517.000000,548.000000,180.00000,37.749202,-122.421016
25%,7.615000e+05,1.000000,1.00000,1092.250000,872.500000,320.00000,37.750128,-122.419210
50%,1.224500e+06,2.500000,1.25000,1481.000000,997.500000,505.00000,37.754051,-122.416142
75%,1.318500e+06,3.000000,2.00000,1867.500000,1026.250000,547.50000,37.755521,-122.411660
max,1.895000e+06,4.000000,3.00000,2191.000000,1350.000000,573.00000,37.767101,-122.407282

In [20]:
tenderloin_df = redfin_year_new.loc[(redfin_year_new['LOCATION'] == 'Tenderloin')]

tenderloin_df

Empty DataFrame
Columns: [PROPERTY TYPE, ADDRESS, CITY, STATE OR PROVINCE, ZIP OR POSTAL CODE, PRICE, BEDS, BATHS, LOCATION, SQUARE FEET, $/SQUARE FEET, HOA/MONTH, LATITUDE, LONGITUDE, BUILT YEAR, COORDINATES]
Index: []

In [26]:
lakeshore_df = redfin_year_new.loc[(redfin_year_new['LOCATION'] == 'Lake')]

lakeshore_df

,PROPERTY TYPE,ADDRESS,CITY,STATE OR PROVINCE,ZIP OR POSTAL CODE,PRICE,BEDS,BATHS,LOCATION,SQUARE FEET,$/SQUARE FEET,HOA/MONTH,LATITUDE,LONGITUDE,BUILT YEAR,COORDINATES
66,Condo/Co-op,1625 Lake St,San Francisco,CA,94121,1549000,2.0,2.0,Lake,1577.0,982.0,200.0,37.785911,-122.477130,1995,"37.785911,-122.4771297"
130,Condo/Co-op,750 Lake St,San Francisco,CA,94118,1895000,2.0,2.0,Lake,NaN,NaN,NaN,37.786716,-122.467725,nan,"37.7867156,-122.46772460000001"
230,Condo/Co-op,756 Lake St,San Francisco,CA,94118,1750000,2.0,2.0,Lake,NaN,NaN,NaN,37.786715,-122.467750,nan,"37.7867145,-122.46775"
250,Single Family Residential,135 15th Ave,San Francisco,CA,94118,4590000,5.0,3.5,Lake,3939.0,1165.0,NaN,37.785534,-122.474609,1912,"37.7855345,-122.4746091"
296,Condo/Co-op,225 26th Ave #1,San Francisco,CA,94121,1959000,4.0,3.5,Lake,2031.0,965.0,391.0,37.785127,-122.486508,2001,"37.785127100000004,-122.4865075"